### ISSUE TITLE
ValueError: Axes should be an instance of GeoAxes, got <class 'matplotlib.axes._subplots.AxesSubplot'>

### ISSUE THREAD

**Issue by abhisek-acharya** [localdevices/pyorc#104]
ds_points_q2.isel(quantile=2).transect.plot(
    ax=p.axes,
    mode="local",
    cmap="rainbow",
    scale=10,
    width=0.003,
    norm=norm,
    add_colorbar=True,
)

This error is arising from the above line of code.

**Comment by hcwinsemius** [comment]
Are you sure that this is the case? That error can only occur when `mode="geographical"`

**Comment by abhisek-acharya** [comment]
Yeah got this error when plotting ds_points_q in both camera and local mode. geographical mode is plotting fine.

**Comment by hcwinsemius** [comment]
Can you perhaps provide a slightly larger example in which you also do the plot of the background frame that then produces the mappable in variable `p` that you use to forward an axes. That will help me reproducing and understanding the error.

**Comment by abhisek-acharya** [comment]
What do you mean by background frame? Larger example in a sense having larger video file size or video which covers more background than just river?

**Comment by hcwinsemius** [comment]
related issue is #80

**Comment by hcwinsemius** [comment]
> What do you mean by background frame? Larger example in a sense having larger video file size or video which covers more background than just river?

I have found a related and still unsolved bug. This is likey the same. We'll take it into the list of priorities.

**Comment by abhisek-acharya** [comment]
Yes issue #80 looks same to me

**Comment by hcwinsemius** [comment]
fix will be added to next release

**Comment by abhisek-acharya** [comment]
Does this issue cover the flipping of the image while plotting the frames?

**Comment by hcwinsemius** [comment]
I cannot reproduce that issue. I need a fully reproducible example in a
separate issue to investigate that.

Op za 14 jan. 2023 07:59 schreef Abhisek Acharya ***@***.***>:
