### ISSUE TITLE
Image from the video frame gets flipped while plotting

### ISSUE THREAD

**Issue by abhisek-acharya** [localdevices/pyorc#105]
You can check it here.

https://github.com/abhisek-acharya/NakkhuSecond/blob/main/NakkhuSecond

In the notebook all of the plots are flipped. If it is by default or some kind of issue?

**Comment by hcwinsemius** [comment]
Reference to likely similar issue where videos are sometimes stored in a rotated form.
 https://stackoverflow.com/questions/53097092/frame-from-video-is-upside-down-after-extracting

**Comment by hcwinsemius** [comment]
I will look into it

**Comment by hcwinsemius** [comment]
@abhisek-acharya thanks again for posting this issue. It took a while to get to it, but it should now be resolved. If you want to try it, you must remove any installed version with conda (after activating the right environment):

``conda remove --force pyopenrivercam``

And then get the latest source code from github. Go to the folder with the code, activate the conda environment and then type:

``pip install .``

**Comment by abdataconsultant** [comment]
Thanks @hcwinsemius. Will surely try.
