### ISSUE TITLE
Error in flow estimation 

### ISSUE THREAD

**Issue by RodrigoMR89** [localdevices/pyorc#143]
Hello, greetings. I'm testing pyorc on some river sections and I've had some difficulties generating the vectors and flows for these sections. I collected the coordinate data using Dgps. In the field I used some GCP points using landscape elements or other ways to identify these points. Attached are the images generated from the information collected in the field.  

Results:

01_camera_configuration:
![config_01](https://github.com/localdevices/pyorc/assets/86724376/de07382b-1672-456c-b1ec-dacf66a0c5ce)
![config_02](https://github.com/localdevices/pyorc/assets/86724376/180b8c55-bad7-45af-935b-ff3d6edd0a0a)
![config_03](https://github.com/localdevices/pyorc/assets/86724376/ffb9b4e5-2f14-4512-a7ba-acdfdcfe46d5)
![config_04](https://github.com/localdevices/pyorc/assets/86724376/a2585b00-9f2a-453a-8b89-574060b1ac79)
![config_05](https://github.com/localdevices/pyorc/assets/86724376/e12e2577-e1cd-4242-835e-f72c73041c5a)

Note: There is a small wooden building (satellite image) that has been moved to another part of the riverbed. However, this is because the imported satellite images are older and do not match the current reality. This is also true for the river. In the satellite images, the river is located to the left of the image, but in reality the path of the river is currently located to the right of the image ( config_03.png), passing through the control points.

02_Process_velocimetry
![config_06](https://github.com/localdevices/pyorc/assets/86724376/9c9fa2ee-9575-4542-8b48-b59286a8534c)
![config_07](https://github.com/localdevices/pyorc/assets/86724376/548e6679-db16-45ae-bd58-a098b718724f)
![config_08](https://github.com/localdevices/pyorc/assets/86724376/27710b11-512f-46db-bac2-bab28ab6387e)

03_Plotting_and_masking_velocimetry
![config_09](https://github.com/localdevices/pyorc/assets/86724376/23b113dc-50ec-4803-ada4-179d39962cd5)
![config_10](https://github.com/localdevices/pyorc/assets/86724376/4c743b3b-26bb-4e94-bcfb-6e6ac30a7ce0)
![config_11](https://github.com/localdevices/pyorc/assets/86724376/1b5cebe6-2ed5-4a2b-b1b3-8050bd1c0234)
![config_12](https://github.com/localdevices/pyorc/assets/86724376/73cf6e9c-a8a7-4278-a32f-541080470c20)
![config_13](https://github.com/localdevices/pyorc/assets/86724376/d9c3c4a0-d7ca-4520-b454-6fb5a15e910b)

04_Extracting_crosssection_velocities_and_discharge
![config_15](https://github.com/localdevices/pyorc/assets/86724376/3cd41744-8bfa-4c7f-b2de-7dea8aa16d60)
![config_16](https://github.com/localdevices/pyorc/assets/86724376/0fee86ac-2d29-47bf-818b-37d04103fe49)
[config_17.pdf](https://github.com/localdevices/pyorc/files/13179308/config_17.pdf)

thanks in advance..

Rodrigo Rodrigues

**Comment by hcwinsemius** [comment]
The perspective is not deep enough to be able to adequately constrain the perspective. Try to find a higher location to take your videos from. Also it may help to measure at least 6 points 3-dimensionally.

The water is also extremely stable so there may not be much to trace and measure flow but that can only be properly seen with an actual video.

**Comment by RodrigoMR89** [comment]
Right. These sections are located in very flat areas where it wasn't possible to record in nadir... And they're very far from where I live... But here's the recording of the section shown... Can you create a filter to estimate these darker regions where the vectors were not created? I have a better quality recording but I can't upload it on github because of the size of the recording.Thanks in advance! 

https://github.com/localdevices/pyorc/assets/86724376/903b28d7-6dbb-4b45-bd3a-7b1394c392ff

**Comment by hcwinsemius** [comment]
I doubt that those tree-reflecting areas will work out. You may try the time_diff filter with a threshold cap of 0. and `abs=False`. 

I would stand on the opposite side of the river where you have a nice steep natural levee (typical for outer bends). You definitely don't have to be nadir but an angle of 30 to 60 degrees is good.

H

**Comment by RodrigoMR89** [comment]
Right. I'll try the filter and the other settings!!!Thanks a lot!!!

**Comment by RodrigoMR89** [comment]
Hi. I tried to find the function - time_diff filter but I couldn't find it in the pyorc base code. I changed the base code but the results (velocity vectors) remained the same. I tried tinkering with the limits of the masks but the results weren't very good...

Another thing, when I changed the gcps coordinates to another cross-section, the cartopy library didn't open the satellite image with the plotted gcp points.  It displayed the following error: 

![image](https://github.com/localdevices/pyorc/assets/86724376/524c1783-ffc3-415d-bbf4-8cd2f01b4152)

**Comment by RodrigoMR89** [comment]
That's it. I've inserted the function (pyorc.Frames.time_diff) into the frame normalization cell in jupyter. Is that correct?
![image](https://github.com/localdevices/pyorc/assets/86724376/c8f65759-e385-46e5-a504-58d5c71212d3)

**Comment by hcwinsemius** [comment]
The code above should work, but now `da_norm` as created on line 1 will be overwritten on line #2. If you want the result of line #1 to go into line #2 you may change the code as follows:

```
da_norm = da.frames.normalize()
da_norm = da_norm.frames.time_diff(abs=False, thres=0.)
da_norm[0].frames.plot(cmap='gray')
```
Now the plot should show the result of both `normalize` and `time_diff` performed in sequence on the frames.

For the comment on the different GCPs. I have too little information to understand why this occurs. It may be that you are using GCPs in real-world coordinates that have a different coordinate system than your `CameraConfig` instance. Say that you have recorded GCPs in lat lon, then you may parse these into your camera configuration as follows:

```
camera_config.set_gcps(
    src=..., # put in your list of [col, row] pixel locations
    dst=..., # put in your list of [x, y, z] real-world coordinates
    crs=4326,  # 4326 coordinates will now be converted on-the-fly from EPSG:4326 to the coordinate system of the camera config
    z_0=...,
    h_ref=....
)

```

**Comment by RodrigoMR89** [comment]
Hello again... I can tell you that I was able to generate the speed data and consequently the flow data using the initial configuration of the program. That is, not inserting the time_diff filter. I have created some virtual sections to compare the results.

![image](https://github.com/localdevices/pyorc/assets/86724376/2b27c6c2-cbe9-4073-83ce-a40eb433dc4b)
![image](https://github.com/localdevices/pyorc/assets/86724376/76b652c7-3d72-484d-a327-39dff7da4580)
![image](https://github.com/localdevices/pyorc/assets/86724376/fedef781-08d3-49a9-958f-14fc5ce2501a)

**Discharge estimates from the cross section**
<xarray.DataArray 'river_flow' (quantile: 5)>
array([ 1.78410393,  0.50871613,  0.11789784, -0.27035904, -0.6718673 ])
Coordinates:
  * quantile  (quantile) float64 0.05 0.25 0.5 0.75 0.95
Attributes:
    standard_name:  river_discharge
    long_name:      River Flow
    units:          m3 s-1 <xarray.DataArray 'river_flow' (quantile: 5)>
array([ 1.95413341,  0.65227036,  0.12427583, -0.18530769, -2.32267325])
Coordinates:
  * quantile  (quantile) float64 0.05 0.25 0.5 0.75 0.95
Attributes:
    standard_name:  river_discharge
    long_name:      River Flow
    units:          m3 s-1 <xarray.DataArray 'river_flow' (quantile: 5)>
array([ 1.41274301,  0.75522128,  0.18536554, -0.28389217, -0.93871204])
Coordinates:
  * quantile  (quantile) float64 0.05 0.25 0.5 0.75 0.95
Attributes:
    standard_name:  river_discharge
    long_name:      River Flow
    units:          m3 s-1 <xarray.DataArray 'river_flow' (quantile: 5)>
array([ 1.72674344,  1.0910377 ,  0.414287  , -0.21717616, -1.20649651])
Coordinates:
  * quantile  (quantile) float64 0.05 0.25 0.5 0.75 0.95
Attributes:
    standard_name:  river_discharge
    long_name:      River Flow
    units:          m3 s-1

Rodrigo

**Comment by hcwinsemius** [comment]
While there are some flow estimates I still think this video is not very adequate. Also the processing has issues. The reprojection covers a much too large area (all the way to the horizon where there really is no detail to see). 

I am currently also working on improvements of the reprojection as this is needed for more strongly distorted videos. This may give you better reprojection results also.

Again for a better result, considering recording from the high bank on the opposite side (or with a drone and then using stabilization).

**Comment by RodrigoMR89** [comment]
Hello again. I'm trying to run the program for other old sections that I have in my database. I don't think the positioning of the camera is right...However, the problem I'm noticing is that I can't get the second tab to load completely...I'm running the program in jupyter and sometimes in dataspell....The loading takes down jupyter and dataspell by 5%...I've tried reducing the number of frames and the quality of the images but it hasn't worked...With regard to using a drone, I'll only be able to use it at a later stage in the campaign....Follow the section of the river below .

![image](https://github.com/localdevices/pyorc/assets/86724376/9d418a10-c267-4b19-b9e5-0c235148606d)

![image](https://github.com/localdevices/pyorc/assets/86724376/fb97e6a5-da7f-484d-b407-3c517384be41)
