### ISSUE TITLE
Parameter "z_0"

### ISSUE THREAD

**Issue by MemoGonzalez23** [localdevices/pyorc#151]
Hello everyone,

I leave this post to ask some questions about the parameter "z_0".

I am working on some videos that I have stored in my computer.
First of all, if I don't have the terrain information, that is, I couldn't measure the water hair in the video I am testing. How do I estimate the value of "z_0"?

Likewise, between what values can "z_0" vary?

Regards

**Comment by hcwinsemius** [comment]
`z_0` is the water level as measured during your survey, measured in the same datum as your control points. This is necessary to be able to interpret the perspective across the water surface. If you only collect one single video, you can measure `z_0` with the same instrumentation as used to measure your control points. You can the simply set `h_ref` to zero when setting up the camera calibration and set `h_a` also to zero when processing velocimetry to indicate that the water level of the video you are processing is the same as the water level as measured during the survey.

This is further explained in a schematic diagram under https://localdevices.github.io/pyorc/user-guide/camera_config/index.html#example-of-survey-situations

Does this answer your question?

**Comment by MemoGonzalez23** [comment]
Yes, thank you very much.
