### ISSUE TITLE
Using lens_position without crs

### ISSUE THREAD

**Issue by Andreas-Bombaert** [localdevices/pyorc#160]
### How did you install pyopenrivercam (mamba / conda or  pip)

conda

### What is the problem?

For my master thesis at UCL we are building an UI using pyorc to process the riverflow, but in our case we don't have the crs for the camera config and we have to use the lens_position, which are [x, y, z] coordinates following the documentation. My question is: from where do these coordinates start? I don't know if it is from the top-left corner of our beacons, or the center of the beacons?

It seems that I do not have the right lens position since pyorc does not find any velocimetry on my video.
I managed to make it work on an other video but when I plot the transect I have inconsistent results.

In the first use notebook I see that for the VGC example the lens_position is set at [7, -2, 3] but from where the X and Y begin?

Thank you for your time,
Andréas

**Comment by hcwinsemius** [comment]
The lens position should be measured in the same coordinate system as all other coordinates. For instance, if you use a GNSS RTK device, you can use the closest UTM system. But you can also use a spirit level or a distometer and measure all coordinates in your own local coordinate system.

Please check out https://localdevices.github.io/pyorc/user-guide/camera_config/index.html#measuring-the-gcp-information for instructions and diagrams. This should explain it quite well.

Please let us know if you have further questions, or if we can close the issue.

**Comment by Andreas-Bombaert** [comment]
Ok, thanks for the quick answer! You can close the issue.

**Comment by hcwinsemius** [comment]
Thanks! Let us know if you have further questions.
