### ISSUE TITLE
pyorc.Video and pyorc.CameraConfig attributes aren't found

### ISSUE THREAD

**Issue by farhanvicena** [localdevices/pyorc#170]
[<ipython-input-55-ccd06af94431>](https://localhost:8080/#) in <cell line: 4>()
      2 #%matplotlib notebook
      3 video_file = "ngwerere/ngwerere_20191103.mp4"
----> 4 video = pyorc.Video(video_file, start_frame=0, end_frame=1)  # we only need one frame
      5 frame = video.get_frame(0, method="rgb")
      6 

AttributeError: module 'pyorc' has no attribute 'Video'

     17 # now we use everything to make a camera configuration
---> 18 cam_config = pyorc.CameraConfig(height=height, width=width, gcps=gcps, crs=32735)

AttributeError: module 'pyorc' has no attribute 'CameraConfig'

I still have no idea why pyorc I installed don't have those attributes. 
After looking at print(dir(pyorc)), I also couldn't find it. Is there anything I did wrong during the installment?

**Comment by hcwinsemius** [comment]
You must post an issue following our template and provide details as per the template for us to look into it. In particular how you installed it is essential to know.

**Comment by hcwinsemius** [comment]
I am assuming that this issue is no longer relevant as we did not receive further feedback.
