### ISSUE TITLE
Real-time Analysis Video

### ISSUE THREAD

**Issue by Ilhamrafi** [localdevices/pyorc#192]
I want to ask, is it possible for me to make a real-time monitoring video using this pyorc? if so, how? Is there any documentation that I can read?

**Comment by hcwinsemius** [comment]
Can you be more specific about the use case? How would you use this?

We have the combination LiveOpenRiverCam and NodeOpenRiverCam for automated real time feeds in case this is what you mean.

**Comment by Ilhamrafi** [comment]
Thank you for the response, appreciate it!
